/* Automatically @generated by tree-sitter */

#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ribbit = 1,
  sym_croak = 2,
  sym_splash = 3,
  sym_gulp = 4,
  sym_burp = 5,
  anon_sym_PLOP = 6,
  anon_sym_HOP = 7,
  anon_sym_LEAP = 8,
  anon_sym_LILY = 9,
  sym_dup = 10,
  sym_swap = 11,
  sym_over = 12,
  sym_add = 13,
  sym_sub = 14,
  sym_mul = 15,
  sym_div = 16,
  sym_equals = 17,
  sym_not_equal = 18,
  sym_less_than = 19,
  sym_greater_than = 20,
  sym_less_eq = 21,
  sym_greater_eq = 22,
  sym_number = 23,
  sym_string = 24,
  sym_identifier = 25,
  sym_comment = 26,
  sym_program = 27,
  sym_statement = 28,
  sym_stack_operation = 29,
  sym_plop = 30,
  sym_control_flow = 31,
  sym_hop = 32,
  sym_leap = 33,
  sym_label_definition = 34,
  sym_stack_manipulation = 35,
  sym_arithmetic = 36,
  sym_comparison = 37,
  aux_sym_program_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ribbit] = "ribbit",
  [sym_croak] = "croak",
  [sym_splash] = "splash",
  [sym_gulp] = "gulp",
  [sym_burp] = "burp",
  [anon_sym_PLOP] = "PLOP",
  [anon_sym_HOP] = "HOP",
  [anon_sym_LEAP] = "LEAP",
  [anon_sym_LILY] = "LILY",
  [sym_dup] = "dup",
  [sym_swap] = "swap",
  [sym_over] = "over",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_equals] = "equals",
  [sym_not_equal] = "not_equal",
  [sym_less_than] = "less_than",
  [sym_greater_than] = "greater_than",
  [sym_less_eq] = "less_eq",
  [sym_greater_eq] = "greater_eq",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym_statement] = "statement",
  [sym_stack_operation] = "stack_operation",
  [sym_plop] = "plop",
  [sym_control_flow] = "control_flow",
  [sym_hop] = "hop",
  [sym_leap] = "leap",
  [sym_label_definition] = "label_definition",
  [sym_stack_manipulation] = "stack_manipulation",
  [sym_arithmetic] = "arithmetic",
  [sym_comparison] = "comparison",
  [aux_sym_program_repeat1] = "program_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ribbit] = sym_ribbit,
  [sym_croak] = sym_croak,
  [sym_splash] = sym_splash,
  [sym_gulp] = sym_gulp,
  [sym_burp] = sym_burp,
  [anon_sym_PLOP] = anon_sym_PLOP,
  [anon_sym_HOP] = anon_sym_HOP,
  [anon_sym_LEAP] = anon_sym_LEAP,
  [anon_sym_LILY] = anon_sym_LILY,
  [sym_dup] = sym_dup,
  [sym_swap] = sym_swap,
  [sym_over] = sym_over,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_equals] = sym_equals,
  [sym_not_equal] = sym_not_equal,
  [sym_less_than] = sym_less_than,
  [sym_greater_than] = sym_greater_than,
  [sym_less_eq] = sym_less_eq,
  [sym_greater_eq] = sym_greater_eq,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym_statement] = sym_statement,
  [sym_stack_operation] = sym_stack_operation,
  [sym_plop] = sym_plop,
  [sym_control_flow] = sym_control_flow,
  [sym_hop] = sym_hop,
  [sym_leap] = sym_leap,
  [sym_label_definition] = sym_label_definition,
  [sym_stack_manipulation] = sym_stack_manipulation,
  [sym_arithmetic] = sym_arithmetic,
  [sym_comparison] = sym_comparison,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ribbit] = {
    .visible = true,
    .named = true,
  },
  [sym_croak] = {
    .visible = true,
    .named = true,
  },
  [sym_splash] = {
    .visible = true,
    .named = true,
  },
  [sym_gulp] = {
    .visible = true,
    .named = true,
  },
  [sym_burp] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLOP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HOP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LEAP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LILY] = {
    .visible = true,
    .named = false,
  },
  [sym_dup] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_over] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_not_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_less_than] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_than] = {
    .visible = true,
    .named = true,
  },
  [sym_less_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_plop] = {
    .visible = true,
    .named = true,
  },
  [sym_control_flow] = {
    .visible = true,
    .named = true,
  },
  [sym_hop] = {
    .visible = true,
    .named = true,
  },
  [sym_leap] = {
    .visible = true,
    .named = true,
  },
  [sym_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_manipulation] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(80);
      ADVANCE_MAP(
        '"', 1,
        '/', 3,
        'A', 17,
        'B', 68,
        'C', 59,
        'D', 29,
        'E', 55,
        'G', 57,
        'H', 42,
        'L', 18,
        'M', 70,
        'N', 41,
        'O', 73,
        'P', 38,
        'R', 28,
        'S', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(103);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(105);
      if (lookahead == '\\') ADVANCE(79);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(107);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(67);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(62);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(49);
      if (lookahead == 'S') ADVANCE(64);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == 'A') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(51);
      END_STATE();
    case 13:
      if (lookahead == 'B') ADVANCE(94);
      END_STATE();
    case 14:
      if (lookahead == 'B') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'B') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'D') ADVANCE(93);
      END_STATE();
    case 17:
      if (lookahead == 'D') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(9);
      if (lookahead == 'I') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(53);
      if (lookahead == 'T') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(58);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(54);
      if (lookahead == 'T') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(61);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(56);
      END_STATE();
    case 25:
      if (lookahead == 'H') ADVANCE(83);
      END_STATE();
    case 26:
      if (lookahead == 'H') ADVANCE(5);
      END_STATE();
    case 27:
      if (lookahead == 'H') ADVANCE(8);
      END_STATE();
    case 28:
      if (lookahead == 'I') ADVANCE(15);
      END_STATE();
    case 29:
      if (lookahead == 'I') ADVANCE(72);
      if (lookahead == 'U') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'I') ADVANCE(66);
      END_STATE();
    case 31:
      if (lookahead == 'K') ADVANCE(82);
      END_STATE();
    case 32:
      if (lookahead == 'L') ADVANCE(74);
      END_STATE();
    case 33:
      if (lookahead == 'L') ADVANCE(95);
      END_STATE();
    case 34:
      if (lookahead == 'L') ADVANCE(98);
      END_STATE();
    case 35:
      if (lookahead == 'L') ADVANCE(63);
      END_STATE();
    case 36:
      if (lookahead == 'L') ADVANCE(48);
      END_STATE();
    case 37:
      if (lookahead == 'L') ADVANCE(7);
      END_STATE();
    case 38:
      if (lookahead == 'L') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 'N') ADVANCE(99);
      END_STATE();
    case 40:
      if (lookahead == 'N') ADVANCE(100);
      END_STATE();
    case 41:
      if (lookahead == 'O') ADVANCE(65);
      END_STATE();
    case 42:
      if (lookahead == 'O') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'O') ADVANCE(4);
      END_STATE();
    case 44:
      if (lookahead == 'O') ADVANCE(50);
      END_STATE();
    case 45:
      if (lookahead == 'P') ADVANCE(90);
      END_STATE();
    case 46:
      if (lookahead == 'P') ADVANCE(87);
      END_STATE();
    case 47:
      if (lookahead == 'P') ADVANCE(85);
      END_STATE();
    case 48:
      if (lookahead == 'P') ADVANCE(84);
      END_STATE();
    case 49:
      if (lookahead == 'P') ADVANCE(88);
      END_STATE();
    case 50:
      if (lookahead == 'P') ADVANCE(86);
      END_STATE();
    case 51:
      if (lookahead == 'P') ADVANCE(91);
      END_STATE();
    case 52:
      if (lookahead == 'P') ADVANCE(37);
      if (lookahead == 'U') ADVANCE(13);
      if (lookahead == 'W') ADVANCE(12);
      END_STATE();
    case 53:
      if (lookahead == 'Q') ADVANCE(101);
      END_STATE();
    case 54:
      if (lookahead == 'Q') ADVANCE(102);
      END_STATE();
    case 55:
      if (lookahead == 'Q') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 'Q') ADVANCE(71);
      END_STATE();
    case 57:
      if (lookahead == 'R') ADVANCE(23);
      if (lookahead == 'U') ADVANCE(36);
      END_STATE();
    case 58:
      if (lookahead == 'R') ADVANCE(92);
      END_STATE();
    case 59:
      if (lookahead == 'R') ADVANCE(43);
      END_STATE();
    case 60:
      if (lookahead == 'R') ADVANCE(47);
      END_STATE();
    case 61:
      if (lookahead == 'R') ADVANCE(77);
      END_STATE();
    case 62:
      if (lookahead == 'S') ADVANCE(25);
      END_STATE();
    case 63:
      if (lookahead == 'S') ADVANCE(97);
      END_STATE();
    case 64:
      if (lookahead == 'S') ADVANCE(75);
      END_STATE();
    case 65:
      if (lookahead == 'T') ADVANCE(76);
      END_STATE();
    case 66:
      if (lookahead == 'T') ADVANCE(81);
      END_STATE();
    case 67:
      if (lookahead == 'T') ADVANCE(22);
      END_STATE();
    case 68:
      if (lookahead == 'U') ADVANCE(60);
      END_STATE();
    case 69:
      if (lookahead == 'U') ADVANCE(10);
      END_STATE();
    case 70:
      if (lookahead == 'U') ADVANCE(33);
      END_STATE();
    case 71:
      if (lookahead == 'U') ADVANCE(11);
      END_STATE();
    case 72:
      if (lookahead == 'V') ADVANCE(96);
      END_STATE();
    case 73:
      if (lookahead == 'V') ADVANCE(20);
      END_STATE();
    case 74:
      if (lookahead == 'Y') ADVANCE(89);
      END_STATE();
    case 75:
      if (lookahead == '_') ADVANCE(19);
      END_STATE();
    case 76:
      if (lookahead == '_') ADVANCE(24);
      END_STATE();
    case 77:
      if (lookahead == '_') ADVANCE(21);
      END_STATE();
    case 78:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 79:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_ribbit);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_croak);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_splash);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_gulp);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_burp);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_PLOP);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_HOP);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LEAP);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_LILY);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_dup);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_swap);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_over);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_add);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_sub);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_not_equal);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_less_than);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_greater_than);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_less_eq);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_greater_eq);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ribbit] = ACTIONS(1),
    [sym_croak] = ACTIONS(1),
    [sym_splash] = ACTIONS(1),
    [sym_gulp] = ACTIONS(1),
    [sym_burp] = ACTIONS(1),
    [anon_sym_PLOP] = ACTIONS(1),
    [anon_sym_HOP] = ACTIONS(1),
    [anon_sym_LEAP] = ACTIONS(1),
    [anon_sym_LILY] = ACTIONS(1),
    [sym_dup] = ACTIONS(1),
    [sym_swap] = ACTIONS(1),
    [sym_over] = ACTIONS(1),
    [sym_add] = ACTIONS(1),
    [sym_sub] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_not_equal] = ACTIONS(1),
    [sym_less_than] = ACTIONS(1),
    [sym_greater_than] = ACTIONS(1),
    [sym_less_eq] = ACTIONS(1),
    [sym_greater_eq] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_program] = STATE(18),
    [sym_statement] = STATE(2),
    [sym_stack_operation] = STATE(8),
    [sym_plop] = STATE(4),
    [sym_control_flow] = STATE(8),
    [sym_hop] = STATE(9),
    [sym_leap] = STATE(9),
    [sym_label_definition] = STATE(8),
    [sym_stack_manipulation] = STATE(8),
    [sym_arithmetic] = STATE(8),
    [sym_comparison] = STATE(8),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ribbit] = ACTIONS(7),
    [sym_croak] = ACTIONS(7),
    [sym_splash] = ACTIONS(7),
    [sym_gulp] = ACTIONS(7),
    [sym_burp] = ACTIONS(7),
    [anon_sym_PLOP] = ACTIONS(9),
    [anon_sym_HOP] = ACTIONS(11),
    [anon_sym_LEAP] = ACTIONS(13),
    [anon_sym_LILY] = ACTIONS(15),
    [sym_dup] = ACTIONS(17),
    [sym_swap] = ACTIONS(17),
    [sym_over] = ACTIONS(17),
    [sym_add] = ACTIONS(19),
    [sym_sub] = ACTIONS(19),
    [sym_mul] = ACTIONS(19),
    [sym_div] = ACTIONS(19),
    [sym_equals] = ACTIONS(21),
    [sym_not_equal] = ACTIONS(21),
    [sym_less_than] = ACTIONS(21),
    [sym_greater_than] = ACTIONS(21),
    [sym_less_eq] = ACTIONS(21),
    [sym_greater_eq] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(3),
    [sym_stack_operation] = STATE(8),
    [sym_plop] = STATE(4),
    [sym_control_flow] = STATE(8),
    [sym_hop] = STATE(9),
    [sym_leap] = STATE(9),
    [sym_label_definition] = STATE(8),
    [sym_stack_manipulation] = STATE(8),
    [sym_arithmetic] = STATE(8),
    [sym_comparison] = STATE(8),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_ribbit] = ACTIONS(7),
    [sym_croak] = ACTIONS(7),
    [sym_splash] = ACTIONS(7),
    [sym_gulp] = ACTIONS(7),
    [sym_burp] = ACTIONS(7),
    [anon_sym_PLOP] = ACTIONS(9),
    [anon_sym_HOP] = ACTIONS(11),
    [anon_sym_LEAP] = ACTIONS(13),
    [anon_sym_LILY] = ACTIONS(15),
    [sym_dup] = ACTIONS(17),
    [sym_swap] = ACTIONS(17),
    [sym_over] = ACTIONS(17),
    [sym_add] = ACTIONS(19),
    [sym_sub] = ACTIONS(19),
    [sym_mul] = ACTIONS(19),
    [sym_div] = ACTIONS(19),
    [sym_equals] = ACTIONS(21),
    [sym_not_equal] = ACTIONS(21),
    [sym_less_than] = ACTIONS(21),
    [sym_greater_than] = ACTIONS(21),
    [sym_less_eq] = ACTIONS(21),
    [sym_greater_eq] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(3),
    [sym_stack_operation] = STATE(8),
    [sym_plop] = STATE(4),
    [sym_control_flow] = STATE(8),
    [sym_hop] = STATE(9),
    [sym_leap] = STATE(9),
    [sym_label_definition] = STATE(8),
    [sym_stack_manipulation] = STATE(8),
    [sym_arithmetic] = STATE(8),
    [sym_comparison] = STATE(8),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_ribbit] = ACTIONS(27),
    [sym_croak] = ACTIONS(27),
    [sym_splash] = ACTIONS(27),
    [sym_gulp] = ACTIONS(27),
    [sym_burp] = ACTIONS(27),
    [anon_sym_PLOP] = ACTIONS(30),
    [anon_sym_HOP] = ACTIONS(33),
    [anon_sym_LEAP] = ACTIONS(36),
    [anon_sym_LILY] = ACTIONS(39),
    [sym_dup] = ACTIONS(42),
    [sym_swap] = ACTIONS(42),
    [sym_over] = ACTIONS(42),
    [sym_add] = ACTIONS(45),
    [sym_sub] = ACTIONS(45),
    [sym_mul] = ACTIONS(45),
    [sym_div] = ACTIONS(45),
    [sym_equals] = ACTIONS(48),
    [sym_not_equal] = ACTIONS(48),
    [sym_less_than] = ACTIONS(48),
    [sym_greater_than] = ACTIONS(48),
    [sym_less_eq] = ACTIONS(48),
    [sym_greater_eq] = ACTIONS(48),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_ribbit] = ACTIONS(51),
    [sym_croak] = ACTIONS(51),
    [sym_splash] = ACTIONS(51),
    [sym_gulp] = ACTIONS(51),
    [sym_burp] = ACTIONS(51),
    [anon_sym_PLOP] = ACTIONS(51),
    [anon_sym_HOP] = ACTIONS(51),
    [anon_sym_LEAP] = ACTIONS(51),
    [anon_sym_LILY] = ACTIONS(51),
    [sym_dup] = ACTIONS(51),
    [sym_swap] = ACTIONS(51),
    [sym_over] = ACTIONS(51),
    [sym_add] = ACTIONS(51),
    [sym_sub] = ACTIONS(51),
    [sym_mul] = ACTIONS(51),
    [sym_div] = ACTIONS(51),
    [sym_equals] = ACTIONS(51),
    [sym_not_equal] = ACTIONS(51),
    [sym_less_than] = ACTIONS(51),
    [sym_greater_than] = ACTIONS(51),
    [sym_less_eq] = ACTIONS(51),
    [sym_greater_eq] = ACTIONS(51),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_ribbit] = ACTIONS(53),
    [sym_croak] = ACTIONS(53),
    [sym_splash] = ACTIONS(53),
    [sym_gulp] = ACTIONS(53),
    [sym_burp] = ACTIONS(53),
    [anon_sym_PLOP] = ACTIONS(53),
    [anon_sym_HOP] = ACTIONS(53),
    [anon_sym_LEAP] = ACTIONS(53),
    [anon_sym_LILY] = ACTIONS(53),
    [sym_dup] = ACTIONS(53),
    [sym_swap] = ACTIONS(53),
    [sym_over] = ACTIONS(53),
    [sym_add] = ACTIONS(53),
    [sym_sub] = ACTIONS(53),
    [sym_mul] = ACTIONS(53),
    [sym_div] = ACTIONS(53),
    [sym_equals] = ACTIONS(53),
    [sym_not_equal] = ACTIONS(53),
    [sym_less_than] = ACTIONS(53),
    [sym_greater_than] = ACTIONS(53),
    [sym_less_eq] = ACTIONS(53),
    [sym_greater_eq] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_ribbit] = ACTIONS(55),
    [sym_croak] = ACTIONS(55),
    [sym_splash] = ACTIONS(55),
    [sym_gulp] = ACTIONS(55),
    [sym_burp] = ACTIONS(55),
    [anon_sym_PLOP] = ACTIONS(55),
    [anon_sym_HOP] = ACTIONS(55),
    [anon_sym_LEAP] = ACTIONS(55),
    [anon_sym_LILY] = ACTIONS(55),
    [sym_dup] = ACTIONS(55),
    [sym_swap] = ACTIONS(55),
    [sym_over] = ACTIONS(55),
    [sym_add] = ACTIONS(55),
    [sym_sub] = ACTIONS(55),
    [sym_mul] = ACTIONS(55),
    [sym_div] = ACTIONS(55),
    [sym_equals] = ACTIONS(55),
    [sym_not_equal] = ACTIONS(55),
    [sym_less_than] = ACTIONS(55),
    [sym_greater_than] = ACTIONS(55),
    [sym_less_eq] = ACTIONS(55),
    [sym_greater_eq] = ACTIONS(55),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_ribbit] = ACTIONS(57),
    [sym_croak] = ACTIONS(57),
    [sym_splash] = ACTIONS(57),
    [sym_gulp] = ACTIONS(57),
    [sym_burp] = ACTIONS(57),
    [anon_sym_PLOP] = ACTIONS(57),
    [anon_sym_HOP] = ACTIONS(57),
    [anon_sym_LEAP] = ACTIONS(57),
    [anon_sym_LILY] = ACTIONS(57),
    [sym_dup] = ACTIONS(57),
    [sym_swap] = ACTIONS(57),
    [sym_over] = ACTIONS(57),
    [sym_add] = ACTIONS(57),
    [sym_sub] = ACTIONS(57),
    [sym_mul] = ACTIONS(57),
    [sym_div] = ACTIONS(57),
    [sym_equals] = ACTIONS(57),
    [sym_not_equal] = ACTIONS(57),
    [sym_less_than] = ACTIONS(57),
    [sym_greater_than] = ACTIONS(57),
    [sym_less_eq] = ACTIONS(57),
    [sym_greater_eq] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_ribbit] = ACTIONS(59),
    [sym_croak] = ACTIONS(59),
    [sym_splash] = ACTIONS(59),
    [sym_gulp] = ACTIONS(59),
    [sym_burp] = ACTIONS(59),
    [anon_sym_PLOP] = ACTIONS(59),
    [anon_sym_HOP] = ACTIONS(59),
    [anon_sym_LEAP] = ACTIONS(59),
    [anon_sym_LILY] = ACTIONS(59),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_over] = ACTIONS(59),
    [sym_add] = ACTIONS(59),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(59),
    [sym_div] = ACTIONS(59),
    [sym_equals] = ACTIONS(59),
    [sym_not_equal] = ACTIONS(59),
    [sym_less_than] = ACTIONS(59),
    [sym_greater_than] = ACTIONS(59),
    [sym_less_eq] = ACTIONS(59),
    [sym_greater_eq] = ACTIONS(59),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_ribbit] = ACTIONS(61),
    [sym_croak] = ACTIONS(61),
    [sym_splash] = ACTIONS(61),
    [sym_gulp] = ACTIONS(61),
    [sym_burp] = ACTIONS(61),
    [anon_sym_PLOP] = ACTIONS(61),
    [anon_sym_HOP] = ACTIONS(61),
    [anon_sym_LEAP] = ACTIONS(61),
    [anon_sym_LILY] = ACTIONS(61),
    [sym_dup] = ACTIONS(61),
    [sym_swap] = ACTIONS(61),
    [sym_over] = ACTIONS(61),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(61),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_equals] = ACTIONS(61),
    [sym_not_equal] = ACTIONS(61),
    [sym_less_than] = ACTIONS(61),
    [sym_greater_than] = ACTIONS(61),
    [sym_less_eq] = ACTIONS(61),
    [sym_greater_eq] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_ribbit] = ACTIONS(63),
    [sym_croak] = ACTIONS(63),
    [sym_splash] = ACTIONS(63),
    [sym_gulp] = ACTIONS(63),
    [sym_burp] = ACTIONS(63),
    [anon_sym_PLOP] = ACTIONS(63),
    [anon_sym_HOP] = ACTIONS(63),
    [anon_sym_LEAP] = ACTIONS(63),
    [anon_sym_LILY] = ACTIONS(63),
    [sym_dup] = ACTIONS(63),
    [sym_swap] = ACTIONS(63),
    [sym_over] = ACTIONS(63),
    [sym_add] = ACTIONS(63),
    [sym_sub] = ACTIONS(63),
    [sym_mul] = ACTIONS(63),
    [sym_div] = ACTIONS(63),
    [sym_equals] = ACTIONS(63),
    [sym_not_equal] = ACTIONS(63),
    [sym_less_than] = ACTIONS(63),
    [sym_greater_than] = ACTIONS(63),
    [sym_less_eq] = ACTIONS(63),
    [sym_greater_eq] = ACTIONS(63),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_ribbit] = ACTIONS(65),
    [sym_croak] = ACTIONS(65),
    [sym_splash] = ACTIONS(65),
    [sym_gulp] = ACTIONS(65),
    [sym_burp] = ACTIONS(65),
    [anon_sym_PLOP] = ACTIONS(65),
    [anon_sym_HOP] = ACTIONS(65),
    [anon_sym_LEAP] = ACTIONS(65),
    [anon_sym_LILY] = ACTIONS(65),
    [sym_dup] = ACTIONS(65),
    [sym_swap] = ACTIONS(65),
    [sym_over] = ACTIONS(65),
    [sym_add] = ACTIONS(65),
    [sym_sub] = ACTIONS(65),
    [sym_mul] = ACTIONS(65),
    [sym_div] = ACTIONS(65),
    [sym_equals] = ACTIONS(65),
    [sym_not_equal] = ACTIONS(65),
    [sym_less_than] = ACTIONS(65),
    [sym_greater_than] = ACTIONS(65),
    [sym_less_eq] = ACTIONS(65),
    [sym_greater_eq] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym_ribbit] = ACTIONS(67),
    [sym_croak] = ACTIONS(67),
    [sym_splash] = ACTIONS(67),
    [sym_gulp] = ACTIONS(67),
    [sym_burp] = ACTIONS(67),
    [anon_sym_PLOP] = ACTIONS(67),
    [anon_sym_HOP] = ACTIONS(67),
    [anon_sym_LEAP] = ACTIONS(67),
    [anon_sym_LILY] = ACTIONS(67),
    [sym_dup] = ACTIONS(67),
    [sym_swap] = ACTIONS(67),
    [sym_over] = ACTIONS(67),
    [sym_add] = ACTIONS(67),
    [sym_sub] = ACTIONS(67),
    [sym_mul] = ACTIONS(67),
    [sym_div] = ACTIONS(67),
    [sym_equals] = ACTIONS(67),
    [sym_not_equal] = ACTIONS(67),
    [sym_less_than] = ACTIONS(67),
    [sym_greater_than] = ACTIONS(67),
    [sym_less_eq] = ACTIONS(67),
    [sym_greater_eq] = ACTIONS(67),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_ribbit] = ACTIONS(69),
    [sym_croak] = ACTIONS(69),
    [sym_splash] = ACTIONS(69),
    [sym_gulp] = ACTIONS(69),
    [sym_burp] = ACTIONS(69),
    [anon_sym_PLOP] = ACTIONS(69),
    [anon_sym_HOP] = ACTIONS(69),
    [anon_sym_LEAP] = ACTIONS(69),
    [anon_sym_LILY] = ACTIONS(69),
    [sym_dup] = ACTIONS(69),
    [sym_swap] = ACTIONS(69),
    [sym_over] = ACTIONS(69),
    [sym_add] = ACTIONS(69),
    [sym_sub] = ACTIONS(69),
    [sym_mul] = ACTIONS(69),
    [sym_div] = ACTIONS(69),
    [sym_equals] = ACTIONS(69),
    [sym_not_equal] = ACTIONS(69),
    [sym_less_than] = ACTIONS(69),
    [sym_greater_than] = ACTIONS(69),
    [sym_less_eq] = ACTIONS(69),
    [sym_greater_eq] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      sym_number,
      sym_string,
  [8] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_identifier,
  [15] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym_identifier,
  [22] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
  [29] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 8,
  [SMALL_STATE(16)] = 15,
  [SMALL_STATE(17)] = 22,
  [SMALL_STATE(18)] = 29,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_operation, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_manipulation, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arithmetic, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_flow, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plop, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hop, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leap, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
unsafe extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_froggy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "froggy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
